
on:
  push:
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'testing folder contents before '
        run: ls

      - uses: actions/checkout@v3
      
      - name: 'testing folder contents after'
        run: ls