
on:
  push:
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'testing get hub action'
        run: pwd

      - name: 'testing printing'
        run: echo fady